apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: employee-app
data:
  PORT: "5000"
  DB_HOST: "10.125.0.3"
  DB_PORT: "3306"
  DB_NAME: "employee"
  BUCKET_NAME: "gcp-devops-project-501115-employee-docs"
  PROJECT_ID: "gcp-devops-project-501115"